import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Jhon Wick
        </h1>
        <h3 className={styles.description}>
          Actor and Artist
        </h3>

        <p className={styles.description}>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo perferendis quod adipisci accusantium magni incidunt nemo iure
        </p>
        <Image className={styles.img} src="/Image/Pic.jfif" alt=""
          width={200}
          height={200} />

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/Image/Pic.jfif" width={30} height={30} alt="pic" />
            <h2> Dummy Test</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
          </div>
          <div className={styles.card}>
            <Image src="/Image/Pic.jfif" width={30} height={30} alt="pic" />
            <h2> Dummy Test</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
          </div>
          <div className={styles.card}>
            <Image src="/Image/Pic.jfif" width={30} height={30} alt="pic" />
            <h2> Dummy Test</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
          </div>
        </div>
        <div className={styles.grid}>
          <a className={styles.Image}>
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>

          <a className={styles.Image}>
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>
          <a
            className={styles.Image}
          >
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>

          <a
            className={styles.Image}
          >
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>
          <a
            className={styles.Image}
          >
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>
          <a
            className={styles.Image}
          >
            <Image src="/Image/Pic.jfif" alt='Pic' width={300}
              height={300} />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
